static_files:
  - name: 'styles.css'
    url: '/static/css/styles.css'
    type: 'css'
    size: '15KB'
    created_at: '2024-12-13'
    description: 'Main stylesheet for the website.'
    version: '1.0.0'

  - name: 'script.js'
    url: '/static/js/script.js'
    type: 'javascript'
    size: '45KB'
    created_at: '2024-12-13'
    description: 'Main JavaScript file for interactive features.'
    version: '1.0.1'

  - name: 'image.png'
    url: '/static/images/image.png'
    type: 'image'
    size: '200KB'
    created_at: '2024-12-13'
    description: 'Header image for the website.'
    version: '1.0.0'

  - name: 'logo.svg'
    url: '/static/images/logo.svg'
    type: 'image'
    size: '50KB'
    created_at: '2024-12-12'
    description: 'Website logo in SVG format.'
    version: '1.1.0'

  - name: 'video.mp4'
    url: '/static/videos/video.mp4'
    type: 'video'
    size: '5MB'
    created_at: '2024-12-10'
    description: 'Introductory video for the website.'
    version: '1.0.0'
